id: P1C9D1A84
initial_creation_type: input
source_metadata:
  title: Jamyang Gyaltsen Series
  language: bo
  description: 'Texts by and about Jamyang Gyaltsen (''jam dbyangs rgyal mtshan, 1870–1940):'
  volume:
    82fcc29b2fb648b88dfaaa103b20aadb:
      title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
        Friend Jamyang Gyaltsen'
      parent: Praise
    3f8485580c01460cb7847b53248e6b2d:
      title: Prayer on the Occasion of the Reading Transmission for the Omniscient
        King of Dharma's Thirteen-Volume Collected Writings
      parent: Prayers
created_at: '2022-02-28T23:33:59.580274'
last_modified_at: '2022-02-28T23:33:59.580276'
statistics:
  total_words: 363
  total_non_words: 49
quality:
  non_words_ratio: 0.13
